### ISSUE TITLE
2.4.0 Start Scanning request failed: Java exception was thrown

### ISSUE THREAD

**Issue by GenesisHypno** [intiface/intiface-central#72]
Grettings Team of Intiface Central.

Intiface Central never worked for me on my Android Phone . I have an Samsung Galaxy Note 8 with Android-Version 9.

When I click on Start Scanning I immediately get the Error: 
Start Scanning request failed: Java exception was thrown

I uploaded 2 Screenshots of the issue 
Thank you 

![Screenshot_20230522-125417](https://github.com/intiface/intiface-central/assets/134281988/161da413-7a2d-40ae-8a46-45433683692c)

![Screenshot_20230522-125421](https://github.com/intiface/intiface-central/assets/134281988/0576b8ac-b67c-4c2a-9e35-57d485be3368)

**Comment by qdot** [comment]
This should be fixed in v2.4.3, which is up on the Play Store now. If you continue to run into issues, please reopen this bug or file a new one.

**Comment by GenesisHypno** [comment]
![Screenshot_20230812-232326](https://github.com/intiface/intiface-central/assets/134281988/e6ff1262-ae4f-41c3-bc9f-418a6c2962c4)

![Screenshot_20230812-232329](https://github.com/intiface/intiface-central/assets/134281988/55014bc4-35ec-4b7e-800e-521555a73269)

Sadly still not fixed. Can't use Intiface-Central with any device.
